// Generated by CoffeeScript 1.3.3
(function() {
  var Entry, exports;

  Nimbus.Auth.setup("Dropbox", "q5yx30gr8mcvq4f", "qy64qphr70lwui5", "droppaper");

  Entry = Nimbus.Model.setup("Entry", ["title", "text", "creation_time", "url"]);

  exports = this;

  exports.Entry = Entry;

}).call(this);
